# Generated by Django 3.2 on 2021-04-17 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('frequency', models.CharField(choices=[('DAILY', 'DAILY'), ('MINUTELY', 'MINUTELY'), ('HOURLY', 'HOURLY')], default='DAILY', max_length=8)),
                ('sunrise', models.DateTimeField()),
                ('sunset', models.DateTimeField()),
                ('moonrise', models.DateTimeField()),
                ('moonset', models.DateTimeField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.FloatField()),
                ('wind_gust', models.FloatField()),
                ('weather', models.CharField(max_length=256)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city')),
            ],
        ),
    ]
