# Generated by Django 3.2 on 2021-04-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_cityweather'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityweather',
            name='temp_day',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityweather',
            name='temp_evening',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityweather',
            name='temp_max',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityweather',
            name='temp_min',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityweather',
            name='temp_morning',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityweather',
            name='temp_night',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
